=== joaofilipevaz/ICD/AP2/src/poema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="poema" type="poemaType"/>
  <xs:complexType name="poemaType">
    <xs:sequence>
      <xs:element type="xs:string" name="autor"/>
      <xs:element type="xs:string" name="tÃ­tulo"/>
      <xs:element type="estrofeType" name="estrofe" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="estrofeType">
    <xs:sequence>
      <xs:element type="xs:string" name="verso" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== joaofilipevaz/ICD/AP2/src/poema.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Poema2.xsl"?>
<poema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="poema.xsd">
	<autor>Luís de Camões</autor>
	<título>Mudam-se os tempos, mudam-se as vontades</título>
	<estrofe>
		<verso>Mudam-se os tempos, mudam-se as vontades,</verso>
		<verso>Muda-se o ser, muda-se a confiança;</verso>
		<verso>Todo o mundo é composto de mudança,</verso>
		<verso>Tomando sempre novas qualidades.</verso>
	</estrofe>
	<estrofe>
		<verso>Continuamente vemos novidades,</verso>
		<verso>Diferentes em tudo da esperança;</verso>
		<verso>Do mal ficam as mágoas na lembrança,</verso>
		<verso>E do bem, se algum houve, as saudades.</verso>
	</estrofe>
	<estrofe>
		<verso>O tempo cobre o chão de verde manto,</verso>
		<verso>Que já coberto foi de neve fria,</verso>
		<verso>E em mim converte em choro o doce canto.</verso>
	</estrofe>
	<estrofe>
		<verso>E, afora este mudar-se cada dia,</verso>
		<verso>Outra mudança faz de mor espanto:</verso>
		<verso>Que não se muda já como soía.</verso>
	</estrofe>
</poema>
